name: CI

on: [push, pull_request]

jobs:
  check-astro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: checks
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run check
